### ISSUE TITLE
On Refactor Branch PostSource should be abstract 🇩🇪  

### ISSUE THREAD

**Issue by germangamboa95** [christopherarter/DotNetTwitterBot#1]
This class should not get instantiated directly. 🇩🇪

**Comment by christopherarter** [comment]
<img width="444" alt="Screen Shot 2020-02-19 at 2 08 42 PM" src="https://user-images.githubusercontent.com/12786153/74866806-73cc0c80-5321-11ea-92f3-bfe79fb7b7f2.png">
